charities/urls.py
from django.conf.urls import patterns, url

from charities import views

urlpatterns = patterns('',
    url(r'^company$', views.company, name='company'),
    url(r'^charity$', views.charity, name='charity'),
    url(r'^user$', views.user, name='user'),
    url(r'^$', views.index, name='index'),
    url(r'^charity/(?P<charity_id>\d+)$', views.charityp, name='charityp'),
)

charitme/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin 


urlpatterns = patterns('',

	# REFER TO THIS AS AN EXAMPLE
	url(r'^example$', 'charitme.views.example', name='example'), 
    
    # url(r'^$', 'charitme.views.home', name='home'),
    url(r'^', include('charities.urls')),
    # url(r'^charity$', 'charitme.views.charity', name='charity'),        
    # url(r'^company$', 'charity.views.company', name='company'),
    # url(r'^charitme/', include('charitme.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

charities/models.py
from django.db import models

class Charity(models.Model):
	name = models.CharField(max_length=200)
	image_url = models.URLField(max_length=200)
	description = models.CharField(max_length=500)

	def __unicode__(self):
		return self.name

class Upvote(models.Model):
	charity = models.ForeignKey(Charity)
	upvotes = models.IntegerField()

	def __unicode__(self):
		return self.charity.name

class Vote(models.Model):
	voter = models.ForeignKey('User')
	link = models.ForeignKey(Charity)

	def __unicode__(self):
		return "%s voted %s" % (self.voter.name, self.link.name)

class Company(models.Model):
	name = models.CharField("Company Title", max_length=200)
	charity = models.ForeignKey(Charity)
	upvote_val = models.FloatField("Value per upvote")
	start_time = models.DateTimeField(auto_now=False, auto_now_add=False)
	end_time = models.DateTimeField(auto_now=False, auto_now_add=False)

	def __unicode__(self):
		return self.name

class User(models.Model):
	name = models.CharField(max_length=100)
	password = models.CharField(max_length=50)

	def __unicode__(self):
		return self.name

charities/forms.py
from django import forms
from django.shortcuts import render

from .models import Company, Charity, User, Upvote

class CompanyForm(forms.ModelForm):
	class Meta: 
		model = Company

class CharityForm(forms.ModelForm):
	class Meta: 
		model = Charity

class UserForm(forms.ModelForm):
	class Meta: 
		model = User

class UpvoteForm(forms.ModelForm):
	class Meta: 
		model = Upvote

charities/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, Http404, get_object_or_404

from .forms import CompanyForm, CharityForm, UserForm, UpvoteForm
from .models import Company, Charity, User, Upvote

def company(request):
	form = CompanyForm(request.POST or None)
	if form.is_valid():
		new_join = form.save(commit=False)
		# name = form.cleaned_data['name']
		# new_join, created = Company.objects.get_or_create(name=name)
		new_join.save()

	template = 'company.html'
	charity_list = Charity.objects.all()
	# return HttpResponse(output)
	context = {'charity_list': charity_list, 'form': form}
	return render(request, template, context)

def charity(request):
	form = CharityForm(request.POST or None)
	if form.is_valid():
		new_join = form.save(commit=False) 
		# name = form.cleaned_data['name']
		# new_join, created = Company.objects.get_or_create(name=name)
		new_join.save()
		u = Upvote(charity=new_join,upvotes=0)
		u.save()

	context = {'form': form}
	template = 'charity.html'
	return render(request, template, context)

def charityp(request, charity_id):
	upvote = get_object_or_404(Upvote, pk=charity_id)
	if 'choice' in request.POST:
		upvote.upvotes += 1
		upvote.save()

	# try:
	# 	selected_choice = p.choice_set.get(pk=request.POST['choice'])
	# except (KeyError, Upvote.DoesNotExist):
 #        # Redisplay the poll voting form.
 #        return render(request, 'index.html', {    
 #        	'poll': p,
 #        	'error_message': "You didn't select a choice.",
 #        })
 #    else:
 #        selected_choice.upvotes += 1
 #        selected_choice.save()
 #        # Always return an HttpResponseRedirect after successfully dealing
 #        # with POST data. This prevents data from being posted twice if a
 #        # user hits the Back button.
 #        return HttpResponseRedirect(reverse('charities:index')

	return render(request, 'charityp.html', {'upvote': upvote})
	
	# return HttpResponse("You're looking at charity %s." % charity_id)

def user(request):
	form = UserForm(request.POST or None)
	if form.is_valid():
		new_join = form.save(commit=False)
		# name = form.cleaned_data['name']
		# new_join, created = Company.objects.get_or_create(name=name)
		new_join.save()

	context = {'form': form}
	template = 'user.html'
	return render(request, template, context)

def index(request):
    # charity_list = Charity.objects.order_by('-upvotes')        
    upvotes_list = Upvote.objects.order_by('-upvotes') 
    # for upvote in upvotes_list:
    	# upvote.

    # output = ', '.join([p.name for p in charity_list])
    # return HttpResponse(output)
    context = {'upvotes_list': upvotes_list,}
    return render(request, 'index.html', context)

charitme/views.py
from django.http import HttpResponse
from django.shortcuts import render

# def home(request):
#     return HttpResponse("Charit.me => This is the current HomePage")

def example(request):
	context = {}
	return render(request, 'example.html', context)



templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Home Page</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
        <!-- Custom styles for this template -->


    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <style>
    	body {
		padding-top: 0px;
		padding-bottom: 0px;
		}
    </style>

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- <title>Clean Blog</title> -->

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom-->

    <link href="css/clean-blog.min.css" rel="stylesheet">
     

     <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body style="">

    <!-- Navigation -->
    <div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url "index" %}">Charit.me</a>
  </div>
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <ul class="nav navbar-nav">
      <li><a href="https://www.hackerleague.org/hackathons/hackru-fall-2014/hacks/charit-dot-me">about</a></li>
    </ul>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Register <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{% url "user" %}">User</a></li>
          <li><a href="{% url "charity" %}">Charity</a></li>
          <li><a href="{% url "company" %}">Funding Campaign</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>
    <!-- Main jumbotron for a primary marketing message or call to action -->
  <!---<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url "index" %}">CHARIT.me</a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Register <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{% url "user" %}">User</a></li>
          <li><a href="{% url "charity" %}">Charity</a></li>
          <li><a href="{% url "company" %}">Campaign</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>-->


    <div class="container">
    	{% block content %}
    	{% endblock %}
      <hr>

      <footer>
        <p>&copy; Charit.Me</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

templates/charity.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

<h3>Register a Charity</h3>

<!-- <form method="POST" action="" role="form"> {% csrf_token %}
  <div class="form-group">
    <label for="id_name">Name:</label>
    {{ form.name }}
  </div>
  <div class="form-group">
    <label for="id_youtube_url">YouTube URL:</label>
    {{ form.youtube_url }}
  </div>
  <div class="form-group">
    <label for="id_description">Description:</label>
    {{ form.description }}
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form> -->

<form method="POST" action=""> {% csrf_token %}
{% bootstrap_form form %}
<input type='submit' value='Post' class='btn btn-primary'>
</form>

{% endblock %}

templates/charityp.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="inner cover">
            <center>
          	<img src = "{{ upvote.charity.image_url }}" width = "300px" height = "300px" class="img-rounded" />
            <h1 class="cover-heading">{{ upvote.charity.name }}</h1>
            <p class="lead">{{ upvote.charity.description }}</p>
            <p class="lead">{{ upvote.upvotes }}</p>
              <form action="" method="POST"> {% csrf_token %}
			    <input type="checkbox" name="choice" value="Upvote {{ upvote.charity.name }}" />
			    <input type="submit" value="Upvote" />
			</form>
            </p>

          </div>

        </div>
        <center>
         <img src = "http://ipe12.mapyourshow.com/mys_shared/ipe12/showfeatures/180/Merck-Banner.jpg" />
         <img src = "http://www.madfellas.com/images/dmImage/SourceImage/ssd-virtual-servers-banner-2-728x90.jpg" /> 
         <center>
      </div>
    </center>

    </div>

<!-- <h3>{{ upvote.charity.name }}</h3>
<h5>{{ upvote.upvotes }}</h5>
<img src = "{{ upvote.charity.image_url }}" class="img-rounded" />
<form action="" method="POST"> {% csrf_token %}
    <input type="checkbox" name="choice" value="Upvote {{ upvote.charity.name }}" />
    <input type="submit" value="Upvote" />
</form> -->
{% endblock %}

templates/company.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

<h3>Sponsor a Charity</h3>

<!-- <form method="POST" action=""> {% csrf_token %}
  <div style="padding:15px">
    company name: {{ form.name }}
  </div>
  <div style="padding:15px">
    Charity to Support:
    {% if charity_list %}
      <select name="charity" id={{form.charity}}>
        {% for charity in charity_list %}
        <option value="{{charity}}">{{charity}}</option>
        {% endfor %}
      </select>
      {% else %}
      <select name="charity">
        <option value="">no charities found</option>
      </select>
    {% endif %}
  </div>
  <div style="padding:15px">
    Dollars per Upvote:
      <select name="upvote_val" id="{{form.upvote_val}}">
        <option value=1>$1</option>
        <option value=2>$2</option>
        <option value=3>$3</option>
        <option value=4>$4</option>
      </select>
  </div>
  <div style="padding:15px">
    <input type='submit' value='Join' class='btn btn-primary'>
  </div>
</form> -->

<form method="POST" action="" role="form"> {% csrf_token %}
{% bootstrap_form form %}
<input type='submit' value='Post' class='btn btn-primary'>
</form>

{% endblock %}

templates/example.html
{% extends 'base.html' %}

{% block content %}

<h1>Example Page</h1>

<!-- Put all of your content in here -->

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
{% load bootstrap3 %}
{% load staticfiles %}

<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->

<header class="intro-header" style="background-image: url({% static 'img/charity2.jpg' %})">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1 style="color:#1D558F;">Charit.me</h1>
            <div class="btn-group">
            <!-- <a href="#" class="btn btn-default">REGISTER</a> -->
            <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown">REGISTER<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <!-- <li><a href="#">About</a></li> -->
              <li><a href="{% url "user" %}">User</a></li>
              <li><a href="{% url "charity" %}">Charity</a></li>
              <li><a href="{% url "company" %}">Funding Campaign</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>


<h2 class="sub-header">Charities</h2>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>upvotes</th>
          <th>name</th>
          <th>description</th>
        </tr>
      </thead>
      {% if upvotes_list %}
      <tbody>
        
        <tr>
        {% for upvote in upvotes_list %}
          <td>{{ forloop.counter }}</td>
          <td>{{ upvote.upvotes }}</td>
          <td><a href = "/charity/{{upvote.charity.id}}">{{ upvote.charity.name }}</td></a>
          <td>{{ upvote.charity.description }}</td>
        </tr>
      </tbody>
      	{% endfor %}
      {% endif %}
    </table>

<!-- {% if charity_list %}
<ul>
{% for charity in charity_list %}
<li>{{ charity.upvotes }} {{ charity.name }}</li>

{% endfor %}
</ul>
{% else %}
<p>No charities are available.</p>
{% endif %}

{% if charity_list %}
<ul>
{% for charity in charity_list %}
<li>{{ charity.upvotes }} {{ charity.name }}</li>

{% endfor %}
</ul>
{% else %}
<p>No charities are available.</p>
{% endif %}
</table> -->

{% endblock %}

templates/user.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

<h3>Register as a User</h3>

<form method="POST" action=""> {% csrf_token %}
{% bootstrap_form form %}
<input type='submit' value='Login' class='btn btn-primary'>
</form>

{% endblock %}

templates/waseemindex.html
{% extends 'base.html' %}

{% block content %}
{% load bootstrap3 %}
{% load staticfiles %}

<<<<<<< HEAD
<h2 class="sub-header">Charities</h2>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>upvotes</th>
          <th>name</th>
          <th>description</th>
        </tr>
      </thead>
      {% if upvotes_list %}
      <tbody>
        
        <tr>
        {% for upvote in upvotes_list %}
          <td>{{ forloop.counter }}</td>
          <td>{{ upvote.upvotes }}</td>
          <td>{{ upvote.charity.name }}</td>
          <td><a href = "/charity/{{upvote.charity.id}}"> Click Me {{ upvote.charity.description }}</td></a>
        </tr>
      </tbody>
      	{% endfor %}
      {% endif %}
    </table>
=======
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->

<header class="intro-header" style="background-image: url({% static 'img/home-bg.jpg' %})">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1 style="color:#1D558F;">Charit.me</h1>
          <hr class="small"></hr>
          <div class="btn-group">
            <!-- <a href="#" class="btn btn-default">REGISTER</a> -->
            <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown">REGISTER<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <!-- <li><a href="#">About</a></li> -->
              <li><a href="{% url "user" %}">User</a></li>
              <li><a href="{% url "charity" %}">Charity</a></li>
              <li><a href="{% url "company" %}">Funding Campaign</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
>>>>>>> ef8c9b364bee2cc582c79aa9411fc7d7989213f5
  </div>
</header>


<h4 class="sub-header">Charities</h4>
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>upvotes</th>
        <th>name</th>
        <th>description</th>
      </tr>
    </thead>
    {% if charity_list %}
    <tbody>
      <tr>
        {% for charity in charity_list %}
        <td><h4>{{ forloop.counter }}</h4></td>
        <td><h6>{{ charity.upvotes }}</h6></td>
        <td><h3>{{ charity.name }}</h3></td>
        <td><h9>{{ charity.description }}</h9></td>
      </tr>
    </tbody>
    {% endfor %}
    {% endif %}
  </table>
</div>

<!-- {% if charity_list %}
<ul>
{% for charity in charity_list %}
<li>{{ charity.upvotes }} {{ charity.name }}</li>

{% endfor %}
</ul>
{% else %}
<p>No charities are available.</p>
{% endif %}

{% if charity_list %}
<ul>
{% for charity in charity_list %}
<li>{{ charity.upvotes }} {{ charity.name }}</li>

{% endfor %}
</ul>
{% else %}
<p>No charities are available.</p>
{% endif %}
</table> -->

{% endblock %}